/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AdminWorkSpace;

import Business.Account.Account;
import Business.ECOSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.RegularExpressionCheck;
import java.awt.CardLayout;
import java.awt.Component;
import Business.Role.AdminRole;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patol
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel2
     */
    private JPanel userProcessContainer;
    private ECOSystem system;

    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, ECOSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateTable();
        populateNetworkComboBox();
        enterpriseJTable.getTableHeader().setFont(new Font("Times New Roman", Font.ITALIC, 23));
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Account userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[3];
                    row[0] = enterprise.getName();
                    row[1] = network.getName();
                    row[2] = userAccount.getUsername();

                    model.addRow(row);
                }
            }
        }
    }

    private void populateNetworkComboBox() {
        JComboBoxCity.removeAllItems();

        for (Network network : system.getNetworkList()) {
            JComboBoxCity.addItem(network);
        }
    }

    private void populateEnterpriseComboBox(Network network) {
        JComboBoxEnterprise.removeAllItems();

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            JComboBoxEnterprise.addItem(enterprise);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JComboBoxCity = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        JComboBoxEnterprise = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        JTextFieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JPasswordFieldpassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseJTable.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise", "City", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseJTable);
        if (enterpriseJTable.getColumnModel().getColumnCount() > 0) {
            enterpriseJTable.getColumnModel().getColumn(0).setResizable(false);
            enterpriseJTable.getColumnModel().getColumn(1).setResizable(false);
            enterpriseJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 920, 140));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel1.setText("City");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        JComboBoxCity.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        JComboBoxCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JComboBoxCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxCityActionPerformed(evt);
            }
        });
        add(JComboBoxCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 270, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel3.setText("Enterprise");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        JComboBoxEnterprise.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        JComboBoxEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JComboBoxEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxEnterpriseActionPerformed(evt);
            }
        });
        add(JComboBoxEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 270, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel4.setText("Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        JTextFieldEmail.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        add(JTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 270, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel5.setText("UserName");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        JPasswordFieldpassword.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        add(JPasswordFieldpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 270, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 22)); // NOI18N
        jLabel2.setText("Kindly provide your Email ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 280, 20));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText(" Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 160, 40));

        btnSubmit.setBackground(new java.awt.Color(0, 0, 0));
        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmit.setBorderPainted(false);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 170, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\TEJAL\\Downloads\\enterprise.jpg")); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 600, 330));
    }// </editor-fold>//GEN-END:initComponents

    private void JComboBoxCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxCityActionPerformed

        Network network = (Network) JComboBoxCity.getSelectedItem();
        if (network != null) {
            populateEnterpriseComboBox(network);
        }

    }//GEN-LAST:event_JComboBoxCityActionPerformed

    private void JComboBoxEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxEnterpriseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBoxEnterpriseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkArea sysAdminwjp = (SystemAdminWorkArea) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

        Enterprise enterprise = (Enterprise) JComboBoxEnterprise.getSelectedItem();

        String password = String.valueOf(JPasswordFieldpassword.getPassword());
        String emailId = JTextFieldEmail.getText();
        String userName = emailId;

        if (password.equals("") && emailId.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter values in all the fields");
            return;
        }

        if (!RegularExpressionCheck.isValidEmailAddress(emailId)) {
            JOptionPane.showMessageDialog(null, " Invalid Username."
                    + "Username should be an email-ID with '_' and '@' as the only allowed special characters but should not start with '_'");
            return;
        }

        if (!RegularExpressionCheck.isValidPassword(password)) {
            JOptionPane.showMessageDialog(null, " Invalid Password."
                    + "Password should contain atleast one lower case, one upper case, one digit, one special character & length should be minimum 6 to max 16 letters");
            return;
        }

        Employee employee = enterprise.getEmployeeDirectory().createEmployee(emailId);

        Account account = enterprise.getUserAccountDirectory().createUserAccount(userName, password, employee, new AdminRole());

        if (account == null) {
            JOptionPane.showMessageDialog(null, "User already exists, please try with another username.");
            clearFields();
            return;
        }
        clearFields();
        populateTable();

    }//GEN-LAST:event_btnSubmitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JComboBoxCity;
    private javax.swing.JComboBox JComboBoxEnterprise;
    private javax.swing.JPasswordField JPasswordFieldpassword;
    private javax.swing.JTextField JTextFieldEmail;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        JTextFieldEmail.setText("");
        JPasswordFieldpassword.setText("");
    }
}
