/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AwarenessCamps;

import Business.Organization.Organization;
import Business.Person.Visitor;
import Business.Person.VisitorDirectory;
import Business.RegularExpressionCheck;
import java.awt.CardLayout;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userInterface.HospitalVisitors.DonorRegistrationForm;

/**
 *
 * @author patol
 */
public class PublicAwarness extends javax.swing.JPanel {

    JPanel rightPanel;
    Organization organization;
    VisitorDirectory vd = new VisitorDirectory();
    
    public PublicAwarness(JPanel rightPanel, Organization organization) {
        initComponents();
        this.rightPanel=rightPanel;
        this.organization = organization;
        ButtonGroup bg = new ButtonGroup();
       
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yesnoGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        emailTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Showing Awareness of Plasma Donation ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, 42));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Help!!!\n\nGreetings of the Day!\n\nSomeone is waiting for your kind anticipation.\nLots of patients from various blood group urgently require a plasma for covid 19 plasma therapy.\nKindly revert us if you could help us to serve patients.\n\n\nThanking You,\nPlasma Management team.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(255, 51, 51));
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 510, 360));

        emailTxt.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 160, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel2.setText("Kindly Provide Email ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 250, 20));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 200, 40));

        btnSubmit.setBackground(new java.awt.Color(0, 0, 0));
        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setBorderPainted(false);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 720, 200, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\TEJAL\\Downloads\\email.jpg")); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 520, 370));
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(emailTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter email");
            return;
        }
        if(!emailTxt.getText().equals("")){


            for(Visitor v: vd.getVisitorList()){
                if(v.getEmail().equals(emailTxt.getText())){
                   JOptionPane.showMessageDialog(null, "Email already exists!");
                    return; 
                }
            }
        boolean validity= RegularExpressionCheck.isValidEmailAddress(emailTxt.getText());
        if(validity){
             final String to = emailTxt.getText();
           String from = "ranedipesh95@gmail.com"; 
            String host = "smtp.gmail.com";
            String user="ranedipesh95@gmail.com";
            String pass = "Gizmodo@2020";
            Properties properties = System.getProperties();  
            properties.setProperty("mail.smtp.host", host); properties.put("mail.smtp.starttls.required", "true");
            properties.put("mail.smtp.starttls.enable", "true");
            properties.put("mail.smtp.host",host);  
            properties.put("mail.smtp.port", "587");  
            properties.put("mail.smtp.auth", "true");  
            boolean sessionDebug=false;
            Session session;
            session = Session.getDefaultInstance(properties,  null);
            session.setDebug(sessionDebug);
            try{
            MimeMessage message = new MimeMessage(session);  
            message.setFrom(new InternetAddress(from));  
            message.setRecipient(Message.RecipientType.TO,new InternetAddress(to));  
            InternetAddress address;
            address = new InternetAddress(to);
            message.setSubject("Awareness Camp");  
            message.setText(jTextArea1.getText() + "\n" + "Please visit awareness camp in "+"Boston");  
            //message.setFileName(from);
            Transport transport = session.getTransport("smtp");
            transport.connect(host,user,pass);
            transport.sendMessage(message, message.getAllRecipients());
            transport.close();
            JOptionPane.showMessageDialog(null, "Please check your email for further details!");
            }
            catch(Exception e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Error!");
            }
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Please re enter email in correct format!");
        }  
     }
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.ButtonGroup yesnoGroup;
    // End of variables declaration//GEN-END:variables
}
