/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.HospitalAdminWorkSpace;

import Business.Organization.Organization;
import Business.Person.Visitor;
import Business.Person.VisitorDirectory;
import Business.RegularExpressionCheck;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userInterface.HospitalVisitors.DonorRegistrationForm;

/**
 *
 * @author patol
 */
public class ManageShowingInterest extends javax.swing.JPanel {

    JPanel rightPanel;
    Organization organization;
    VisitorDirectory vd = new VisitorDirectory();
    
    public ManageShowingInterest(JPanel rightPanel, Organization organization) {
        initComponents();
        this.rightPanel=rightPanel;
        this.organization = organization;
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioBtnYes);
        bg.add(jRadioBtnNo);
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yesnoGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioBtnYes = new javax.swing.JRadioButton();
        jRadioBtnNo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        emailTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Showing Awareness of Plasma Donation ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, 42));

        jRadioBtnYes.setBackground(new java.awt.Color(255, 255, 255));
        yesnoGroup.add(jRadioBtnYes);
        jRadioBtnYes.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jRadioBtnYes.setText("YES");
        jRadioBtnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtnYesActionPerformed(evt);
            }
        });
        add(jRadioBtnYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        jRadioBtnNo.setBackground(new java.awt.Color(255, 255, 255));
        yesnoGroup.add(jRadioBtnNo);
        jRadioBtnNo.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jRadioBtnNo.setText("NO");
        add(jRadioBtnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Improvements in medical techniques and pharmacological anti-reject therapies have made organ transplantation a powerful and valid way to treat diseases. Thanks to this, and to the relevance that mass media put on it, the number of donors is constantly increasing.\nDonors are usually persons who have been involved in serious accidents and are kept artificially alive though cerebral death has been stated. In such patients is extremely difficult to maintain acceptable vital parameters for a long time, and any variation in them can lead to the loss of organs. \nMoreover, after the organs have been taken from the body, they can be stored for very few hours and the transplant must take place in the shortest period possible.\n\n");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(255, 51, 51));
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 510, 360));

        emailTxt.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 160, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel2.setText("Kindly Provide Email ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 250, 20));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 200, 40));

        btnSubmit.setBackground(new java.awt.Color(0, 0, 0));
        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setBorderPainted(false);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 690, 200, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioBtnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtnYesActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jRadioBtnYesActionPerformed

    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(emailTxt.getText().equals("")&& jRadioBtnYes.isSelected()==false && jRadioBtnNo.isSelected()==false){
            JOptionPane.showMessageDialog(null, "Please enter email and choose one of the options-Yes or No.");
            return;
        }
        if(!emailTxt.getText().equals("")){


            for(Visitor v: vd.getVisitorList()){
                if(v.getEmail().equals(emailTxt.getText())){
                   JOptionPane.showMessageDialog(null, "Email already exists!");
                    return; 
                }
            }
        boolean validity= RegularExpressionCheck.isValidEmailAddress(emailTxt.getText());
        if(validity){
            if (jRadioBtnYes.isSelected())
            {
                //yes
                vd.createVisitor(emailTxt.getText(),true);
                DonorRegistrationForm donorRegistration = new DonorRegistrationForm(rightPanel, organization, emailTxt.getText());
                rightPanel.add("donorRegistration", donorRegistration);
                CardLayout layout = (CardLayout) rightPanel.getLayout();
                layout.next(rightPanel);
            }
            else if(jRadioBtnNo.isSelected())
            {
                //no
                RegularExpressionCheck.c++;
                vd.createVisitor(emailTxt.getText(),false);
                JOptionPane.showMessageDialog(null, "Thanks for your time!");
                //To-do send email
                return;
            }
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Please re enter email in correct format!");
        }  
     }
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioBtnNo;
    private javax.swing.JRadioButton jRadioBtnYes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.ButtonGroup yesnoGroup;
    // End of variables declaration//GEN-END:variables
}
